title: MyAITask
description: AI productivity hub: free tools, templates, affiliate picks, and paid guest posts.
url: https://example.com
theme: minima
markdown: kramdown
paginate: 10
paginate_path: "/page:num/"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

minima:
  skin: auto

permalink: /:categories/:year/:month/:day/:title/
